### ISSUE TITLE
FastBusFactory 제공

### ISSUE THREAD

**Issue by iolo** [day1co/fastbus#14]
PR #12 를 통해 두 개의 `FastBus` 구현체가 존재하게되니... FastBusFactory가 필요합니다.

구현체 선택 전략:
1. 팩토리 메소드 인자로 지정
2. 환경변수(ex. `FASTBUS_BACKEND`)에 따라 redis 또는 cloudpubsub 구현체를 명시적으로 선택
3. `@google-cloud/pubsub`  의존성이 있으면  cloudpubsub, `ioredis` 의존성이 있으면 redis 구현체를 자동으로 선택
4. 위의 규칙에 의해 선택할 수 있는 구현체가 없으면... 기본(fallback)으로 dummy 구현체 선택.

최종적으로 사용자는 다음과 같이 `FastBus` 인스턴스를 얻을 수 있음
```js
const bus = FastBusFactory.create(options);
// 또는 좀 더 거창하게...
// const bus = FastBusFactory.getInstance().create(options);
```

**Comment by soomtong** [comment]
local 기반으로 돌아가는 dummy 구현체도 하나 있어야겠군요.

**Comment by iolo** [comment]
> local 기반으로 돌아가는 dummy 구현체도 하나 있어야겠군요.

보통은 그런데...(쓰는 쪽 테스트를 위해서도 필요하죠),
없으면 에러내도 무방.
